### ISSUE TITLE
sweetalert2.scss inclusion is redundant

### ISSUE THREAD

**Issue by toverux** [limonte/sweetalert2-webpack-demo#5]
[styles.scss](https://github.com/limonte/sweetalert2-webpack-demo/blob/master/styles.scss) still includes SweetAlert's style, though the all-in-one build of Swal is used since fba0254de89162847a78b6232722e1463a8d8138.
Related build steps (ex. https://github.com/limonte/sweetalert2-webpack-demo/blob/master/webpack.config.babel.js#L16) can be removed also if we delete styles.scss.

**Comment by limonte** [comment]
Removed in https://github.com/limonte/sweetalert2-webpack-demo/commit/2bd4dc6d25a9cb53772b39573f7da2f507f63a66 thanks for reporting!

While doing this task I discovered the tiny regression in `6.10.0` - `swal.version` was empty, that issue is fixed in `6.10.1` and CI now testing against both `dist/sweetalert2.js` and `dist/sweetalert2.all.min.js` :rocket:
